// Code generated by protoc-gen-go-neofs. DO NOT EDIT.

package subnet

import "github.com/nspcc-dev/neofs-api-go/v2/util/proto"

func (x *SubnetInfo) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.NestedStructureSize(1, x.Id)
	size += proto.NestedStructureSize(2, x.Owner)
	return size
}

func (x *SubnetInfo) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	n, err = proto.NestedStructureMarshal(1, buf[offset:], x.Id)
	if err != nil {
		return nil, err
	}
	offset += n
	n, err = proto.NestedStructureMarshal(2, buf[offset:], x.Owner)
	if err != nil {
		return nil, err
	}
	offset += n
	return buf, nil
}
