// Code generated by protoc-gen-go-neofs. DO NOT EDIT.

package status

import "github.com/nspcc-dev/neofs-api-go/v2/util/proto"

func (x *Status_Detail) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.UInt32Size(1, x.Id)
	size += proto.BytesSize(2, x.Value)
	return size
}

func (x *Status_Detail) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	offset += proto.UInt32Marshal(1, buf[offset:], x.Id)
	offset += proto.BytesMarshal(2, buf[offset:], x.Value)
	return buf, nil
}

func (x *Status) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.UInt32Size(1, x.Code)
	size += proto.StringSize(2, x.Message)
	for i := range x.Details {
		size += proto.NestedStructureSize(3, x.Details[i])
	}
	return size
}

func (x *Status) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	offset += proto.UInt32Marshal(1, buf[offset:], x.Code)
	offset += proto.StringMarshal(2, buf[offset:], x.Message)
	for i := range x.Details {
		n, err = proto.NestedStructureMarshal(3, buf[offset:], x.Details[i])
		if err != nil {
			return nil, err
		}
		offset += n
	}
	return buf, nil
}
