// Code generated by protoc-gen-go-neofs. DO NOT EDIT.

package storagegroup

import "github.com/nspcc-dev/neofs-api-go/v2/util/proto"

func (x *StorageGroup) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.UInt64Size(1, x.ValidationDataSize)
	size += proto.NestedStructureSize(2, x.ValidationHash)
	size += proto.UInt64Size(3, x.ExpirationEpoch)
	for i := range x.Members {
		size += proto.NestedStructureSize(4, x.Members[i])
	}
	return size
}

func (x *StorageGroup) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	offset += proto.UInt64Marshal(1, buf[offset:], x.ValidationDataSize)
	n, err = proto.NestedStructureMarshal(2, buf[offset:], x.ValidationHash)
	if err != nil {
		return nil, err
	}
	offset += n
	offset += proto.UInt64Marshal(3, buf[offset:], x.ExpirationEpoch)
	for i := range x.Members {
		n, err = proto.NestedStructureMarshal(4, buf[offset:], x.Members[i])
		if err != nil {
			return nil, err
		}
		offset += n
	}
	return buf, nil
}
