// Code generated by protoc-gen-go-neofs. DO NOT EDIT.

package container

import "github.com/nspcc-dev/neofs-api-go/v2/util/proto"

func (x *Container_Attribute) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.StringSize(1, x.Key)
	size += proto.StringSize(2, x.Value)
	return size
}

func (x *Container_Attribute) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	offset += proto.StringMarshal(1, buf[offset:], x.Key)
	offset += proto.StringMarshal(2, buf[offset:], x.Value)
	return buf, nil
}

func (x *Container) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.NestedStructureSize(1, x.Version)
	size += proto.NestedStructureSize(2, x.OwnerId)
	size += proto.BytesSize(3, x.Nonce)
	size += proto.UInt32Size(4, x.BasicAcl)
	for i := range x.Attributes {
		size += proto.NestedStructureSize(5, x.Attributes[i])
	}
	size += proto.NestedStructureSize(6, x.PlacementPolicy)
	return size
}

func (x *Container) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	n, err = proto.NestedStructureMarshal(1, buf[offset:], x.Version)
	if err != nil {
		return nil, err
	}
	offset += n
	n, err = proto.NestedStructureMarshal(2, buf[offset:], x.OwnerId)
	if err != nil {
		return nil, err
	}
	offset += n
	offset += proto.BytesMarshal(3, buf[offset:], x.Nonce)
	offset += proto.UInt32Marshal(4, buf[offset:], x.BasicAcl)
	for i := range x.Attributes {
		n, err = proto.NestedStructureMarshal(5, buf[offset:], x.Attributes[i])
		if err != nil {
			return nil, err
		}
		offset += n
	}
	n, err = proto.NestedStructureMarshal(6, buf[offset:], x.PlacementPolicy)
	if err != nil {
		return nil, err
	}
	offset += n
	return buf, nil
}
