// Code generated by protoc-gen-go-neofs. DO NOT EDIT.

package tombstone

import "github.com/nspcc-dev/neofs-api-go/v2/util/proto"

func (x *Tombstone) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.UInt64Size(1, x.ExpirationEpoch)
	size += proto.BytesSize(2, x.SplitId)
	for i := range x.Members {
		size += proto.NestedStructureSize(3, x.Members[i])
	}
	return size
}

func (x *Tombstone) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	offset += proto.UInt64Marshal(1, buf[offset:], x.ExpirationEpoch)
	offset += proto.BytesMarshal(2, buf[offset:], x.SplitId)
	for i := range x.Members {
		n, err = proto.NestedStructureMarshal(3, buf[offset:], x.Members[i])
		if err != nil {
			return nil, err
		}
		offset += n
	}
	return buf, nil
}
