// Code generated by protoc-gen-go-neofs. DO NOT EDIT.

package session

import "github.com/nspcc-dev/neofs-api-go/v2/util/proto"

func (x *CreateRequest_Body) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.NestedStructureSize(1, x.OwnerId)
	size += proto.UInt64Size(2, x.Expiration)
	return size
}

func (x *CreateRequest_Body) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	n, err = proto.NestedStructureMarshal(1, buf[offset:], x.OwnerId)
	if err != nil {
		return nil, err
	}
	offset += n
	offset += proto.UInt64Marshal(2, buf[offset:], x.Expiration)
	return buf, nil
}

func (x *CreateRequest) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.NestedStructureSize(1, x.Body)
	size += proto.NestedStructureSize(2, x.MetaHeader)
	size += proto.NestedStructureSize(3, x.VerifyHeader)
	return size
}

func (x *CreateRequest) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	n, err = proto.NestedStructureMarshal(1, buf[offset:], x.Body)
	if err != nil {
		return nil, err
	}
	offset += n
	n, err = proto.NestedStructureMarshal(2, buf[offset:], x.MetaHeader)
	if err != nil {
		return nil, err
	}
	offset += n
	n, err = proto.NestedStructureMarshal(3, buf[offset:], x.VerifyHeader)
	if err != nil {
		return nil, err
	}
	offset += n
	return buf, nil
}

func (x *CreateResponse_Body) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.BytesSize(1, x.Id)
	size += proto.BytesSize(2, x.SessionKey)
	return size
}

func (x *CreateResponse_Body) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	offset += proto.BytesMarshal(1, buf[offset:], x.Id)
	offset += proto.BytesMarshal(2, buf[offset:], x.SessionKey)
	return buf, nil
}

func (x *CreateResponse) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.NestedStructureSize(1, x.Body)
	size += proto.NestedStructureSize(2, x.MetaHeader)
	size += proto.NestedStructureSize(3, x.VerifyHeader)
	return size
}

func (x *CreateResponse) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	n, err = proto.NestedStructureMarshal(1, buf[offset:], x.Body)
	if err != nil {
		return nil, err
	}
	offset += n
	n, err = proto.NestedStructureMarshal(2, buf[offset:], x.MetaHeader)
	if err != nil {
		return nil, err
	}
	offset += n
	n, err = proto.NestedStructureMarshal(3, buf[offset:], x.VerifyHeader)
	if err != nil {
		return nil, err
	}
	offset += n
	return buf, nil
}
