// Code generated by protoc-gen-go-neofs. DO NOT EDIT.

package accounting

import "github.com/nspcc-dev/neofs-api-go/v2/util/proto"

func (x *Decimal) StableSize() (size int) {
	if x == nil {
		return
	}
	size += proto.Int64Size(1, x.Value)
	size += proto.UInt32Size(2, x.Precision)
	return size
}

func (x *Decimal) StableMarshal(buf []byte) ([]byte, error) {
	if x == nil {
		return []byte{}, nil
	}
	if buf == nil {
		buf = make([]byte, x.StableSize())
	}
	var err error
	var offset, n int
	_, _, _ = err, offset, n
	offset += proto.Int64Marshal(1, buf[offset:], x.Value)
	offset += proto.UInt32Marshal(2, buf[offset:], x.Precision)
	return buf, nil
}
